archivesBaseName = 'fetchplan-jmix-test-scenarios'

jmix {
    entitiesEnhancing {
        enabled = false
    }
}

dependencies {
    compileOnly 'io.jmix.core:jmix-core'
    compileOnly 'javax.persistence:javax.persistence-api:2.2'
    compileOnly 'org.springframework:spring-context'
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}